### ISSUE TITLE
Switchen van wsgicors naar wsgicoers

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/uriregistry#14]
Indien van toepassing. In de requirements wsgicors dependency verwijderen en toevoegen wsgicoers==0.8.2. In prodcution.ini ```use = egg:wsgicors#middleware``` vervangen door ```use = egg:wsgicoers#middleware```.

**Comment by BartSaelen** [comment]
gebruikt momenteel geen cors, maar zou dit wel moeten hebben?

**Comment by koenedaele** [comment]
Lijkt eerder bij de deployment te horen.

**Comment by koenedaele** [comment]
Dit moet aangepast worden in deployment.
