### ISSUE TITLE
Application: uri and url

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/uriregistry#6]
@dieuska Do you know why we have both of them? Was there a good usecase for that?

**Comment by dieuska** [comment]
No, not a use case to have them both.
As it is now, we only need the url of the application, used in https://github.com/OnroerendErfgoed/uriregistry/blob/f99dfd461bbea56aa613aab6a3ada9034feaf8d4/uriregistry/utils.py#L17 to query the application.

**Comment by koenedaele** [comment]
Changed url to service_url. 

Meaning: the uri identifies an application (does not have to be a http uri, could be a urn as well). The service_url identifies the service that can be asked for references, eg. https://inventaris.onroerenderfgoed.be/references.
