### ISSUE TITLE
Improved performance

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/uriregistry#8]
At the moment, checking of references is done in serial (one application at a time). See https://github.com/OnroerendErfgoed/uriregistry/blob/master/uriregistry/views.py#L39 Once we start having to query a large number of applications it starts taking a long time.

Can we query more than one app at the same time?

**Comment by koenedaele** [comment]
@claeyswo Aan jou toegewezen zodat we deze niet uit het oog verliezen

**Comment by claeyswo** [comment]
Wsl gelijkaardig aan wat we hier gedaan hebben: https://github.com/OnroerendErfgoed/projectcodes/blob/42d54b6af7b0fed7222852243f6b3dd40addab65/projectcodes/views/html.py#L56
